- id: doi:10.1038/s41928-025-01509-9
  type: paper
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41928-025-01509-9/MediaObjects/41928_2025_1509_Fig1_HTML.png
  buttons:
    - type: paper
      link: https://www.nature.com/articles/s41928-025-01509-9
  tags:
    - flexible electronics
    - neural implants

- id: doi:10.1002/ange.202517897
  type: paper
  image: https://onlinelibrary.wiley.com/cms/asset/3e59edf6-169f-4ba5-9f87-c0c35413dfbd/ange70239-gra-0001-m.jpg
  buttons:
    - type: paper
      link: https://onlinelibrary.wiley.com/doi/full/10.1002/anie.202517897
  tags:
    - organic electronics
    - photopolymerization
 

- id: doi:10.1038/s44222-024-00180-7
  type: paper
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs44222-024-00180-7/MediaObjects/44222_2024_180_Fig1_HTML.png  
  buttons:
    - type: paper
      link: https://www.nature.com/articles/s44222-024-00180-7
  tags:
    - organic electronics
    - OECTs
