- id: doi:10.1038/s41928-025-01509-9
  type: paper
  image: https://www.nature.com/articles/s41928-025-01509-9/figures/1
  buttons:
    - type: paper
      link: https://www.nature.com/articles/s41928-025-01509-9
  tags:
    - flexible electronics
    - neural implants

- id: doi:10.1002/ange.202517897
  image: https://onlinelibrary.wiley.com/cms/asset/3e59edf6-169f-4ba5-9f87-c0c35413dfbd/ange70239-gra-0001-m.jpg

- id: doi:10.1038/s44222-024-00180-7
  image: https://www.nature.com/articles/s44222-024-00180-7/figures/1
